### PR TITLE
Enable latexml test

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-ogc/issues/21#issuecomment-468264446
 - https://github.com/metanorma/metanorma-ogc/issues/21#issuecomment-469086448

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 it's failing somehow...

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis 

Problem with 
`/usr/local/Cellar/metanorma/1.1.6/bin/metanorma --type standoc --extensions xml /private/tmp/metanorma-test-20190331-82893-1un33m3/test-standoc.adoc`

I cannot reproduce it locally, but I will investigate it after https://github.com/metanorma/metanorma/issues/41

```
/usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/inline.rb:113:in `sub': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/inline.rb:113:in `block in stem_parse'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/inline.rb:112:in `stem_parse'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/blocks.rb:50:in `block (2 levels) in stem'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/blocks.rb:49:in `block in stem'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:293:in `initialize'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:254:in `new'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:254:in `with'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/utils.rb:116:in `noko'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/blocks.rb:48:in `stem'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/utils.rb:96:in `convert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1261:in `content'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/base.rb:183:in `block in middle'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/base.rb:182:in `middle'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/base.rb:154:in `block in makexml1'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:293:in `initialize'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:254:in `new'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:254:in `with'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/utils.rb:116:in `noko'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/base.rb:154:in `makexml1'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/base.rb:160:in `makexml'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/base.rb:141:in `document'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/utils.rb:96:in `convert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-0.3.10/lib/metanorma/input/asciidoc.rb:8:in `process'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.5/lib/metanorma/standoc/processor.rb:25:in `input_to_isodoc'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-0.3.10/lib/metanorma/compile.rb:100:in `process_input'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-0.3.10/lib/metanorma/compile.rb:17:in `compile'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-cli-1.1.6/exe/metanorma:137:in `<top (required)>'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/bin/metanorma:22:in `load'
```

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you move ahead with this or are you stuck? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse unfortunately I didn't had time to continue the investigation since last comment I will look at it

**Comment by CAMOBAP795** [comment]
Fixed here https://github.com/metanorma/metanorma-standoc/pull/63

**Comment by CAMOBAP795** [comment]
Please let's keep it open till next release of `metanorma-cli` & `metanorma-standoc`

**Comment by opoudjis** [comment]
metanorma-standoc has been released. metanorma-cli is WIP with @abunashir, so has not been released this cycle.

**Comment by opoudjis** [comment]
Let's wait for next release. metanorma-cli has been delayed anyway.

**Comment by ronaldtse** [comment]
Passing so merging.

**Pull request merged**
