### PR TITLE
#34 fix broken CI

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #34

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
- OSX looks good
 - Linux still broken I'm investigating it

**Comment by ronaldtse** [comment]
@CAMOBAP795 can we merge this? Why do we have to `brew unlink`? Do we need to do that with formula on real installation?

**Comment by ronaldtse** [comment]
@CAMOBAP795 Linux install failed here.

**Comment by CAMOBAP795** [comment]
@ronaldtse yep I'm checking this

**Comment by ronaldtse** [comment]
@CAMOBAP795 all passing! Please merge when ready. Thanks!

**Comment by CAMOBAP795** [comment]
This happens because of `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` defined for some reason
I'm trying to clear it inside of the formula

**Comment by CAMOBAP795** [comment]
- https://discourse.brew.sh/t/how-to-remove-environment-variable-before-system-call/7091

**Comment by CAMOBAP795** [comment]
A new issue occurs starting from today

```
Error: An exception occurred within a child process:
  NameError: undefined local variable or method `python' for #<Language::Python::Virtualenv::Virtualenv:0x0000000002824f68>
Did you mean?  @python
##[error]Process completed with exit code 1.
```

**Comment by CAMOBAP795** [comment]
One more post created https://discourse.brew.sh/t/nameerror-undefined-local-variable-or-method-python-for-language-virtualenv/7098

**Comment by ronaldtse** [comment]
@CAMOBAP795 we're almost there :-)

**Comment by CAMOBAP795** [comment]
Merging linux issue will be fixed in scope of https://github.com/metanorma/homebrew-metanorma/issues/33

**Pull request merged**
