### PR TITLE
Add idnits-2.16.02 resource

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-linux-setup/issues/10

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
> @CAMOBAP795 perhaps we should make idnits into a separate formula?

`idnits` may conflict with the existing one, but when we install it 'privately' in venv (like we do it right now) there will be no such conflict

**Comment by CAMOBAP795** [comment]
I just wondering is https://files.pythonhosted.org/packages/source/i/idnits/idnits-3.0.0.tar.gz have the same functionality as https://tools.ietf.org/tools/idnits/idnits-2.16.02 or it's just a py wrapper for bash script, let me check

**Comment by ronaldtse** [comment]
@CAMOBAP795 is this ready to be merged? I think idnits 3.0 may be the version for the new RFC XML version 3.

**Comment by CAMOBAP795** [comment]
@ronaldtse yep, let me just restart one failed step (because of network issue)

**Pull request merged**
