### PR TITLE
Add travis matrix

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
Failed because on OSX 10.12 default ruby doesn't support tls v1.2, https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#macos-built-in-ruby

**Comment by CAMOBAP795** [comment]
Can be fixed with https://medium.com/@katopz/how-to-upgrade-openssl-8d005554401 

@ronaldtse I can help with this, let me know is it makes sense to support 10.12 for us ?http://gs.statcounter.com/os-version-market-share/macos/desktop/united-states-of-america

**Comment by ronaldtse** [comment]
@CAMOBAP795 let's drop 10.12, it will be too annoying to support it. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse after detailed investigation I have found that problem is in https://github.com/metanorma/html2doc/commit/906b2a45a61365d83b1110880292f41c7cf3f50c because most of OSX distribution have ruby 2.3 out of the box without upgrade this is why it fails on all versions

Looking for solution

**Comment by opoudjis** [comment]
With a minimum of OSX 10.13, you've locked out 28% of the market, and you're betting that Metanorma users are going to be enthusiastic system upgraders. Given how OSX has been going from bad to worse, and given that you want Metanorma to be used by non-programmers, that is not necessarily a good idea. Then again, Metanorma is in so much difficulty already, there's no point complaining about this.

**Comment by CAMOBAP795** [comment]
@opoudjis good point but in fact, OS version upgrade on OSX much easier than system ruby version upgrade)

If we don't run CI on the particular version it doesn't mean that we don't support it

As I said I'm looking for a way how we can use non-system ruby in metanorma formula

**Comment by ronaldtse** [comment]
Well, this is an argument to keep Ruby 2.3 support since 10.12 is Ruby 2.3 by default.

The Ruby version/gem bundling issue can be solved if we have a packager, such as https://github.com/metanorma/metanorma/issues/61 .

**Comment by opoudjis** [comment]
Christ.

So am I putting Ruby 2.3 back in? Really?

Just bear in mind that  if Travis is going to take two days to run, I'm simply going to ignore it when doing gem releases. Running Travis and Appveyor, for three different versions of Ruby, and for a bunch of open development interdependencies, is all very nice and robust; it's also comically unworkable. And @CAMOBAP795, it *definitely* means the only branch that pre-release Travis testing will ever see is a single dev branch on every gem; the notion the we will multiply this testing by five different branches is even more unworkable.

https://github.com/metanorma/metanorma/issues/54 is the visualisation of all dependencies in Metanorma and Relaton. It is a flat tree, but not as flat as I'd like.

**Comment by CAMOBAP795** [comment]
> So am I putting Ruby 2.3 back in? Really?

@ronaldtse @opoudjis please let me finish research about how to specify Ruby version in formula, maybe there is a way how we can accomplish this

**Pull request merged**
