### PR TITLE
Feature/add python2 idnits xml2rfc

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-linux-setup/issues/10

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
Same issue as described here https://github.com/metanorma/homebrew-metanorma/pull/19#issuecomment-498448081

**Comment by ronaldtse** [comment]
@CAMOBAP795 all builds still failing.

**Comment by CAMOBAP795** [comment]
@ronaldtse yes (because https://github.com/metanorma/homebrew-metanorma/pull/19#issuecomment-498448081

**Comment by CAMOBAP795** [comment]
https://discourse.brew.sh/t/gem-based-formula-error-requires-ruby-version-2-4-0/4948

**Pull request merged**
